accelerator: gpu
accumulate_grad_batches: 1
annotation: ./data/mimic_cxr/annotation.json
base_dir: ./data/mimic_cxr/images
batch_size: 16
beam_size: 3
biogpt_model: microsoft/biogpt
ckpt_file: save2/biogpt_v1/mimic_cxr_biogpt_epochepoch=24.ckpt
dataset: mimic_cxr
delta_file: null
devices: 1
diversity_penalty: 0
do_sample: false
encoder_lr: 1.0e-06
end_sym: </s>
every_n_train_steps: 0
freeze_vm: true
global_only: false
gradient_clip_val: null
image_dir: C:/Users/David/Downloads/archive (1)/images/images_normalized
learning_rate: 1.0e-05
length_penalty: 2.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
llm_alpha: 16
llm_r: 16
llm_use_lora: false
lora_dropout: 0.1
low_resource: false
max_epochs: 60
max_length: 100
max_new_tokens: 120
min_new_tokens: 80
no_repeat_ngram_size: 2
num_beam_groups: 1
num_nodes: 1
num_sanity_val_steps: 2
num_workers: 8
precision: bf16-mixed
prefetch_factor: 4
projections_csv: C:/Users/David/Downloads/archive (1)/indiana_projections.csv
repetition_penalty: 2.0
reports_csv: C:/Users/David/Downloads/chex_clinical_project/data/normalized_reports.csv
resume_training: false
savedmodel_path: save5/biogpt_v1
scorer_types:
- Bleu_4
- CIDEr
strategy: auto
temperature: 1.0
test: false
test_batch_size: 16
val_batch_size: 16
val_check_interval: 1.0
validate: false
vis_alpha: 16
vis_r: 16
vis_use_lora: false
vision_model: microsoft/swin-base-patch4-window7-224
weights:
- 0.5
- 0.5
